// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/leminhthai/train-ticket/booking-service/internal/repository"
	"github.com/leminhthai/train-ticket/booking-service/internal/service"
)

// Injectors from wire.go:

func InitializeApp(sqlDB *sql.DB) *App {
	queries := ProvideQueries(sqlDB)
	bookingRepository := repository.NewBookingRepository(sqlDB, queries)
	bookingService := service.NewBookingService(bookingRepository)
	paymentRepository := repository.NewPaymentRepository(sqlDB, queries)
	paymentService := service.NewPaymentService(bookingRepository, paymentRepository)
	app := &App{
		BookingService: bookingService,
		PaymentService: paymentService,
	}
	return app
}

// wire.go:

var BookingSet = wire.NewSet(repository.NewBookingRepository, service.NewBookingService)

var PaymentSet = wire.NewSet(repository.NewPaymentRepository, service.NewPaymentService)
