// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/leminhthai/train-ticket/user-service/internal/repository"
	"github.com/leminhthai/train-ticket/user-service/internal/service"
)

// Injectors from wire.go:

// InitializeApp tạo toàn bộ dependency. Một injector, một lần *sql.DB. Chạy `make wire` sau khi sửa Set/App.
func InitializeApp(sqlDB *sql.DB) *App {
	queries := ProvideQueries(sqlDB)
	userRepository := repository.NewUserRepository(queries)
	userService := service.NewUserService(userRepository)
	app := &App{
		UserService: userService,
	}
	return app
}

// wire.go:

// UserSet nhóm provider cho user (queries -> repo -> service).
var UserSet = wire.NewSet(
	ProvideQueries, repository.NewUserRepository, service.NewUserService,
)
