# Stage 1 — Build
FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o bin/booking-service ./cmd/server/main.go

# Stage 2 — Run
FROM alpine:latest

RUN apk --no-cache add ca-certificates tzdata
WORKDIR /root/

COPY --from=builder /app/bin/booking-service .
COPY --from=builder /app/configs ./configs

EXPOSE 8084

CMD ["./booking-service"]